/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdherenceLog {
  'takenAt' : Time,
  'confirmed' : boolean,
  'medicineId' : MedicineId,
}
export interface HealthCheckinResponse {
  'date' : string,
  'questionsAndAnswers' : Array<{ 'question' : string, 'answer' : string }>,
  'session' : string,
  'timestamp' : Time,
}
export interface Medicine {
  'id' : MedicineId,
  'dosage' : string,
  'source' : string,
  'name' : string,
  'time' : string,
  'addedAt' : Time,
}
export type MedicineId = bigint;
export type PhoneNumber = string;
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'weight' : bigint,
  'principal' : Principal,
  'preferredLanguage' : string,
  'name' : string,
  'medicalConditions' : Array<string>,
  'doctorContact' : [] | [PhoneNumber],
  'bloodGroup' : string,
  'primaryCaregiverContact' : PhoneNumber,
  'registrationComplete' : boolean,
  'secondaryCaregiverContact' : [] | [PhoneNumber],
}
export interface _SERVICE {
  'addMedicine' : ActorMethod<[string, string, string, string], MedicineId>,
  'createEmergencyAlert' : ActorMethod<[string], undefined>,
  'deleteMedicine' : ActorMethod<[MedicineId], undefined>,
  'getHealthCheckinsByDate' : ActorMethod<
    [string],
    [] | [HealthCheckinResponse]
  >,
  'getMedicinesByTime' : ActorMethod<[string], Array<Medicine>>,
  'getMissedDoses' : ActorMethod<[], Array<Medicine>>,
  'getTodaysAdherence' : ActorMethod<[], Array<AdherenceLog>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'logAdherence' : ActorMethod<[MedicineId, boolean], undefined>,
  'submitHealthCheckin' : ActorMethod<
    [string, string, Array<{ 'question' : string, 'answer' : string }>],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      Array<string>,
      [] | [PhoneNumber],
      PhoneNumber,
      [] | [PhoneNumber],
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];