/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MedicineId = IDL.Nat;
export const Time = IDL.Int;
export const HealthCheckinResponse = IDL.Record({
  'date' : IDL.Text,
  'questionsAndAnswers' : IDL.Vec(
    IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })
  ),
  'session' : IDL.Text,
  'timestamp' : Time,
});
export const Medicine = IDL.Record({
  'id' : MedicineId,
  'dosage' : IDL.Text,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'addedAt' : Time,
});
export const AdherenceLog = IDL.Record({
  'takenAt' : Time,
  'confirmed' : IDL.Bool,
  'medicineId' : MedicineId,
});
export const PhoneNumber = IDL.Text;
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Nat,
  'principal' : IDL.Principal,
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Vec(IDL.Text),
  'doctorContact' : IDL.Opt(PhoneNumber),
  'bloodGroup' : IDL.Text,
  'primaryCaregiverContact' : PhoneNumber,
  'registrationComplete' : IDL.Bool,
  'secondaryCaregiverContact' : IDL.Opt(PhoneNumber),
});

export const idlService = IDL.Service({
  'addMedicine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MedicineId],
      [],
    ),
  'createEmergencyAlert' : IDL.Func([IDL.Text], [], []),
  'deleteMedicine' : IDL.Func([MedicineId], [], []),
  'getHealthCheckinsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthCheckinResponse)],
      ['query'],
    ),
  'getMedicinesByTime' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'getMissedDoses' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getTodaysAdherence' : IDL.Func([], [IDL.Vec(AdherenceLog)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'logAdherence' : IDL.Func([MedicineId, IDL.Bool], [], []),
  'submitHealthCheckin' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(PhoneNumber),
        PhoneNumber,
        IDL.Opt(PhoneNumber),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MedicineId = IDL.Nat;
  const Time = IDL.Int;
  const HealthCheckinResponse = IDL.Record({
    'date' : IDL.Text,
    'questionsAndAnswers' : IDL.Vec(
      IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })
    ),
    'session' : IDL.Text,
    'timestamp' : Time,
  });
  const Medicine = IDL.Record({
    'id' : MedicineId,
    'dosage' : IDL.Text,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'addedAt' : Time,
  });
  const AdherenceLog = IDL.Record({
    'takenAt' : Time,
    'confirmed' : IDL.Bool,
    'medicineId' : MedicineId,
  });
  const PhoneNumber = IDL.Text;
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Nat,
    'principal' : IDL.Principal,
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Vec(IDL.Text),
    'doctorContact' : IDL.Opt(PhoneNumber),
    'bloodGroup' : IDL.Text,
    'primaryCaregiverContact' : PhoneNumber,
    'registrationComplete' : IDL.Bool,
    'secondaryCaregiverContact' : IDL.Opt(PhoneNumber),
  });
  
  return IDL.Service({
    'addMedicine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MedicineId],
        [],
      ),
    'createEmergencyAlert' : IDL.Func([IDL.Text], [], []),
    'deleteMedicine' : IDL.Func([MedicineId], [], []),
    'getHealthCheckinsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthCheckinResponse)],
        ['query'],
      ),
    'getMedicinesByTime' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'getMissedDoses' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getTodaysAdherence' : IDL.Func([], [IDL.Vec(AdherenceLog)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'logAdherence' : IDL.Func([MedicineId, IDL.Bool], [], []),
    'submitHealthCheckin' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text })),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(PhoneNumber),
          PhoneNumber,
          IDL.Opt(PhoneNumber),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };