/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Nat;
export const AlertType = IDL.Variant({
  'emergency' : IDL.Null,
  'missedDose' : IDL.Null,
  'healthUpdate' : IDL.Null,
});
export const Time = IDL.Int;
export const Phone = IDL.Text;
export const Contact = IDL.Record({ 'name' : IDL.Text, 'phone' : Phone });
export const MedicationId = IDL.Nat;
export const DoseLog = IDL.Record({
  'medicationId' : MedicationId,
  'timestamp' : Time,
  'confirmedByVoice' : IDL.Bool,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'principal' : IDL.Principal,
  'preferredLanguage' : IDL.Text,
  'doctor' : Contact,
  'name' : IDL.Text,
  'caregiver' : Contact,
});
export const Alert = IDL.Record({
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Medication = IDL.Record({
  'id' : MedicationId,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'scheduledTimes' : IDL.Vec(IDL.Text),
  'frequency' : IDL.Nat,
});
export const Mood = IDL.Variant({
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
});
export const HealthCheckIn = IDL.Record({
  'mood' : Mood,
  'timestamp' : Time,
  'sideEffects' : IDL.Text,
  'symptoms' : IDL.Text,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([AlertId], [], []),
  'addMedication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createAlert' : IDL.Func([AlertType, IDL.Text, Time], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, Contact, Contact],
      [],
      [],
    ),
  'deleteMedication' : IDL.Func([MedicationId], [], []),
  'getDoseLogsForToday' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'listMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
  'listRecentCheckIns' : IDL.Func([], [IDL.Vec(HealthCheckIn)], ['query']),
  'logDose' : IDL.Func([MedicationId, Time, IDL.Bool], [], []),
  'submitCheckIn' : IDL.Func([IDL.Text, IDL.Text, Mood, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Nat;
  const AlertType = IDL.Variant({
    'emergency' : IDL.Null,
    'missedDose' : IDL.Null,
    'healthUpdate' : IDL.Null,
  });
  const Time = IDL.Int;
  const Phone = IDL.Text;
  const Contact = IDL.Record({ 'name' : IDL.Text, 'phone' : Phone });
  const MedicationId = IDL.Nat;
  const DoseLog = IDL.Record({
    'medicationId' : MedicationId,
    'timestamp' : Time,
    'confirmedByVoice' : IDL.Bool,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'principal' : IDL.Principal,
    'preferredLanguage' : IDL.Text,
    'doctor' : Contact,
    'name' : IDL.Text,
    'caregiver' : Contact,
  });
  const Alert = IDL.Record({
    'id' : AlertId,
    'alertType' : AlertType,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Medication = IDL.Record({
    'id' : MedicationId,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'scheduledTimes' : IDL.Vec(IDL.Text),
    'frequency' : IDL.Nat,
  });
  const Mood = IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
  });
  const HealthCheckIn = IDL.Record({
    'mood' : Mood,
    'timestamp' : Time,
    'sideEffects' : IDL.Text,
    'symptoms' : IDL.Text,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([AlertId], [], []),
    'addMedication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'createAlert' : IDL.Func([AlertType, IDL.Text, Time], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, Contact, Contact],
        [],
        [],
      ),
    'deleteMedication' : IDL.Func([MedicationId], [], []),
    'getDoseLogsForToday' : IDL.Func([], [IDL.Vec(DoseLog)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'listMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
    'listRecentCheckIns' : IDL.Func([], [IDL.Vec(HealthCheckIn)], ['query']),
    'logDose' : IDL.Func([MedicationId, Time, IDL.Bool], [], []),
    'submitCheckIn' : IDL.Func([IDL.Text, IDL.Text, Mood, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };