/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledged' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type AlertId = bigint;
export type AlertType = { 'emergency' : null } |
  { 'missedDose' : null } |
  { 'healthUpdate' : null };
export interface Contact { 'name' : string, 'phone' : Phone }
export interface DoseLog {
  'medicationId' : MedicationId,
  'timestamp' : Time,
  'confirmedByVoice' : boolean,
}
export interface HealthCheckIn {
  'mood' : Mood,
  'timestamp' : Time,
  'sideEffects' : string,
  'symptoms' : string,
}
export interface Medication {
  'id' : MedicationId,
  'dosage' : string,
  'name' : string,
  'notes' : string,
  'scheduledTimes' : Array<string>,
  'frequency' : bigint,
}
export type MedicationId = bigint;
export type Mood = { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null };
export type Phone = string;
export interface Profile {
  'age' : bigint,
  'principal' : Principal,
  'preferredLanguage' : string,
  'doctor' : Contact,
  'name' : string,
  'caregiver' : Contact,
}
export type Time = bigint;
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[AlertId], undefined>,
  'addMedication' : ActorMethod<
    [string, string, bigint, Array<string>, string],
    undefined
  >,
  'createAlert' : ActorMethod<[AlertType, string, Time], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, bigint, string, Contact, Contact],
    undefined
  >,
  'deleteMedication' : ActorMethod<[MedicationId], undefined>,
  'getDoseLogsForToday' : ActorMethod<[], Array<DoseLog>>,
  'getProfile' : ActorMethod<[], Profile>,
  'listAlerts' : ActorMethod<[], Array<Alert>>,
  'listMedications' : ActorMethod<[], Array<Medication>>,
  'listRecentCheckIns' : ActorMethod<[], Array<HealthCheckIn>>,
  'logDose' : ActorMethod<[MedicationId, Time, boolean], undefined>,
  'submitCheckIn' : ActorMethod<[string, string, Mood, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];