/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type MedicationId = bigint;
export interface Contact {
    name: string;
    phone: Phone;
}
export type AlertId = bigint;
export type Phone = string;
export interface HealthCheckIn {
    mood: Mood;
    timestamp: Time;
    sideEffects: string;
    symptoms: string;
}
export interface Profile {
    age: bigint;
    principal: Principal;
    preferredLanguage: string;
    doctor: Contact;
    name: string;
    caregiver: Contact;
}
export interface DoseLog {
    medicationId: MedicationId;
    timestamp: Time;
    confirmedByVoice: boolean;
}
export interface Medication {
    id: MedicationId;
    dosage: string;
    name: string;
    notes: string;
    scheduledTimes: Array<string>;
    frequency: bigint;
}
export interface Alert {
    id: AlertId;
    alertType: AlertType;
    acknowledged: boolean;
    message: string;
    timestamp: Time;
}
export enum AlertType {
    emergency = "emergency",
    missedDose = "missedDose",
    healthUpdate = "healthUpdate"
}
export enum Mood {
    fair = "fair",
    good = "good",
    poor = "poor"
}
export interface backendInterface {
    acknowledgeAlert(alertId: AlertId): Promise<void>;
    addMedication(name: string, dosage: string, frequency: bigint, scheduledTimes: Array<string>, notes: string): Promise<void>;
    createAlert(alertType: AlertType, message: string, timestamp: Time): Promise<void>;
    createOrUpdateProfile(name: string, age: bigint, preferredLanguage: string, doctor: Contact, caregiver: Contact): Promise<void>;
    deleteMedication(medicationId: MedicationId): Promise<void>;
    getDoseLogsForToday(): Promise<Array<DoseLog>>;
    getProfile(): Promise<Profile>;
    listAlerts(): Promise<Array<Alert>>;
    listMedications(): Promise<Array<Medication>>;
    listRecentCheckIns(): Promise<Array<HealthCheckIn>>;
    logDose(medicationId: MedicationId, timestamp: Time, confirmedByVoice: boolean): Promise<void>;
    submitCheckIn(symptoms: string, sideEffects: string, mood: Mood, timestamp: Time): Promise<void>;
}
import type { Alert as _Alert, AlertId as _AlertId, AlertType as _AlertType, HealthCheckIn as _HealthCheckIn, Mood as _Mood, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addMedication(arg0: string, arg1: string, arg2: bigint, arg3: Array<string>, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createAlert(arg0: AlertType, arg1: string, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(to_candid_AlertType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: bigint, arg2: string, arg3: Contact, arg4: Contact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteMedication(arg0: MedicationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedication(arg0);
            return result;
        }
    }
    async getDoseLogsForToday(): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoseLogsForToday();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoseLogsForToday();
            return result;
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async listAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlerts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlerts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMedications(): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedications();
            return result;
        }
    }
    async listRecentCheckIns(): Promise<Array<HealthCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecentCheckIns();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecentCheckIns();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async logDose(arg0: MedicationId, arg1: Time, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDose(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDose(arg0, arg1, arg2);
            return result;
        }
    }
    async submitCheckIn(arg0: string, arg1: string, arg2: Mood, arg3: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckIn(arg0, arg1, to_candid_Mood_n13(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckIn(arg0, arg1, to_candid_Mood_n13(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_AlertType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_HealthCheckIn_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthCheckIn): HealthCheckIn {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: _Mood;
    timestamp: _Time;
    sideEffects: string;
    symptoms: string;
}): {
    mood: Mood;
    timestamp: Time;
    sideEffects: string;
    symptoms: string;
} {
    return {
        mood: from_candid_Mood_n11(_uploadFile, _downloadFile, value.mood),
        timestamp: value.timestamp,
        sideEffects: value.sideEffects,
        symptoms: value.symptoms
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    alertType: _AlertType;
    acknowledged: boolean;
    message: string;
    timestamp: _Time;
}): {
    id: AlertId;
    alertType: AlertType;
    acknowledged: boolean;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n6(_uploadFile, _downloadFile, value.alertType),
        acknowledged: value.acknowledged,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
}): Mood {
    return "fair" in value ? Mood.fair : "good" in value ? Mood.good : "poor" in value ? Mood.poor : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    missedDose: null;
} | {
    healthUpdate: null;
}): AlertType {
    return "emergency" in value ? AlertType.emergency : "missedDose" in value ? AlertType.missedDose : "healthUpdate" in value ? AlertType.healthUpdate : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthCheckIn>): Array<HealthCheckIn> {
    return value.map((x)=>from_candid_HealthCheckIn_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AlertType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} {
    return value == Mood.fair ? {
        fair: null
    } : value == Mood.good ? {
        good: null
    } : value == Mood.poor ? {
        poor: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    emergency: null;
} | {
    missedDose: null;
} | {
    healthUpdate: null;
} {
    return value == AlertType.emergency ? {
        emergency: null
    } : value == AlertType.missedDose ? {
        missedDose: null
    } : value == AlertType.healthUpdate ? {
        healthUpdate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
