/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PhoneNumber = string;
export type Time = bigint;
export interface HealthCheckinResponse {
    date: string;
    questionsAndAnswers: Array<{
        question: string;
        answer: string;
    }>;
    session: string;
    timestamp: Time;
}
export type MedicineId = bigint;
export interface Medicine {
    id: MedicineId;
    dosage: string;
    source: string;
    name: string;
    time: string;
    addedAt: Time;
}
export interface AdherenceLog {
    takenAt: Time;
    confirmed: boolean;
    medicineId: MedicineId;
}
export interface UserProfile {
    age: bigint;
    weight: bigint;
    principal: Principal;
    preferredLanguage: string;
    name: string;
    medicalConditions: Array<string>;
    doctorContact?: PhoneNumber;
    bloodGroup: string;
    primaryCaregiverContact: PhoneNumber;
    registrationComplete: boolean;
    secondaryCaregiverContact?: PhoneNumber;
}
export interface backendInterface {
    addMedicine(name: string, dosage: string, time: string, source: string): Promise<MedicineId>;
    createEmergencyAlert(note: string): Promise<void>;
    deleteMedicine(medicineId: MedicineId): Promise<void>;
    getHealthCheckinsByDate(date: string): Promise<HealthCheckinResponse | null>;
    getMedicinesByTime(timeOfDay: string): Promise<Array<Medicine>>;
    getMissedDoses(): Promise<Array<Medicine>>;
    getTodaysAdherence(): Promise<Array<AdherenceLog>>;
    getUserProfile(): Promise<UserProfile | null>;
    logAdherence(medicineId: MedicineId, confirmed: boolean): Promise<void>;
    submitHealthCheckin(session: string, date: string, questionsAndAnswers: Array<{
        question: string;
        answer: string;
    }>): Promise<void>;
    updateUserProfile(name: string, age: bigint, weight: bigint, bloodGroup: string, preferredLanguage: string, medicalConditions: Array<string>, doctorContact: PhoneNumber | null, primaryCaregiverContact: PhoneNumber, secondaryCaregiverContact: PhoneNumber | null, registrationComplete: boolean): Promise<void>;
}
import type { HealthCheckinResponse as _HealthCheckinResponse, PhoneNumber as _PhoneNumber, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMedicine(arg0: string, arg1: string, arg2: string, arg3: string): Promise<MedicineId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createEmergencyAlert(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmergencyAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmergencyAlert(arg0);
            return result;
        }
    }
    async deleteMedicine(arg0: MedicineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getHealthCheckinsByDate(arg0: string): Promise<HealthCheckinResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthCheckinsByDate(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthCheckinsByDate(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicinesByTime(arg0: string): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesByTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesByTime(arg0);
            return result;
        }
    }
    async getMissedDoses(): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissedDoses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissedDoses();
            return result;
        }
    }
    async getTodaysAdherence(): Promise<Array<AdherenceLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysAdherence();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysAdherence();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async logAdherence(arg0: MedicineId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logAdherence(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAdherence(arg0, arg1);
            return result;
        }
    }
    async submitHealthCheckin(arg0: string, arg1: string, arg2: Array<{
        question: string;
        answer: string;
    }>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHealthCheckin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHealthCheckin(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: Array<string>, arg6: PhoneNumber | null, arg7: PhoneNumber, arg8: PhoneNumber | null, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
}
function from_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthCheckinResponse]): HealthCheckinResponse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhoneNumber]): PhoneNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: bigint;
    principal: Principal;
    preferredLanguage: string;
    name: string;
    medicalConditions: Array<string>;
    doctorContact: [] | [_PhoneNumber];
    bloodGroup: string;
    primaryCaregiverContact: _PhoneNumber;
    registrationComplete: boolean;
    secondaryCaregiverContact: [] | [_PhoneNumber];
}): {
    age: bigint;
    weight: bigint;
    principal: Principal;
    preferredLanguage: string;
    name: string;
    medicalConditions: Array<string>;
    doctorContact?: PhoneNumber;
    bloodGroup: string;
    primaryCaregiverContact: PhoneNumber;
    registrationComplete: boolean;
    secondaryCaregiverContact?: PhoneNumber;
} {
    return {
        age: value.age,
        weight: value.weight,
        principal: value.principal,
        preferredLanguage: value.preferredLanguage,
        name: value.name,
        medicalConditions: value.medicalConditions,
        doctorContact: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.doctorContact)),
        bloodGroup: value.bloodGroup,
        primaryCaregiverContact: value.primaryCaregiverContact,
        registrationComplete: value.registrationComplete,
        secondaryCaregiverContact: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.secondaryCaregiverContact))
    };
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhoneNumber | null): [] | [_PhoneNumber] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
